# autogenerated by txs
#include:iftex
#include:infwarerr
\csname#S
\empty#S
\expandafter#S
\x#S
\x{arg1}{arg2}#S
\x{arg1}{arg2}{arg3}#S
\y#S
\__file_name=iftex.sty#S
\__file_name=infwarerr.sty#S
\__hook iftex#S
\__hook infwarerr#S
\unprocessedoptions-iftex.sty#S
\unprocessedoptions-infwarerr.sty#S
csnameendcsname#S
iftex.sty#S
infwarerr.sty#S
