# autogenerated by txs
#include:luabidi
#include:xkeyval
\HebrewFromGregorian{arg1}{arg2}{arg3}{arg4}{arg5}#S
\HebrewMonthNameInEnglish{arg1}{arg2}#S
\HebrewMonthName{arg1}{arg2}#S
\HebrewYearName{arg1}#S
\Hebrewtoday#S
\hebrewdate{arg1}{arg2}{arg3}#S
\hebrewsetreg#S
\hebrewtoday#S
\thetmpA
\thetmpC
\thetmpE
