# autogenerated by txs
#include:etoolbox
#include:keyval
\LogreqDTDVersion#S
\comment#S
\do#S
\do{arg1}#S
\expandafter#S
\protect#S
\DeclareLogreqAttribute#S
\DeclareLogreqContainer#S
\DeclareLogreqElement#S
\\logrequest#S
\__file_name=etoolbox.sty#S
\__file_name=logreq.def#S
\__hook etoolbox#S
\logrequest#S
\ltxrequest#S
\unprocessedoptions-etoolbox.sty#S
__file_name=logreq.def#S
csnameendcsname#S
etoolbox.sty#S
logreq.def#S
