# autogenerated by txs
\DeclareTextMathSymbol{arg1}{arg2}{arg3}{arg4}{arg5}#S
\DeclareTextSymbol{arg1}{arg2}{arg3}#S
\LastDeclaredEncoding#S
\csname#S
\expandafter#S
\expandafter{arg1}#S
\?-tmcmd#S
\halign#S
