# autogenerated by txs
\0#S
\1#S
\2#S
\3#S
\8#S
\9#S
\UCSPU#S
\UCSPUrange{arg1}{arg2}#S
\UCSPU{arg1}#S
\csname#S
\fontencoding#S
\foreignlanguage#S
\pdfstringdefPreHook#S
\pdfstringdef{arg1}{arg2}#S
\selectfont#S
\selectlanguage#S
\ucspu#S
\unichar#S
\unichar{arg1}#S
\__file_name=hpdftex.def#S
\__file_name=hyperref.sty#S
\__hook hyperref#S
\unprocessedoptions-hyperref.sty#S
__file_name=hpdftex.def#S
csnameendcsname#S
hpdftex.def#S
hyperref.sty#S
